[project]
name = "zernike2d"
version = "0.1.0"
description = ""
authors = [
    {name = "Giovanni Marzioni", email = "marzioni.2060629@studenti.uniroma1.it"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib==3.8.4",
    "numpy==1.26.4",
    "pandas==2.2.2",
    "scipy==1.13.0",
    "tqdm==4.66.4",
    "zepyros @ git+https://github.com/LuGiova/zepyros.git",
    "scikit-learn==1.5.0"
]

[tool.poetry]
package-mode = false

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
